### ISSUE TITLE
checking unique key on update is problematic

### ISSUE THREAD

**Issue by camel-chased** [balderdashy/sails-redis#53]
`"version": "0.10.3",`
i have a user with some email, and i want that this email to be unique ;>
everything is ok till i want update some fields, i can not because email is already there
i think solution for this is to check email in db and email i want to save if they are equal do not check uniqueness because email is already there so it must be unique
`checkUniqueConstraints` in `lib/database/index.js`

**Comment by ralph-rush** [comment]
ok i figure it out, this is the partial code form `lib/database/index.js` , i dont have time to pull request so

```javascript
Database.prototype.update = function update(collectionName, criteria, values, cb) {
  var self = this,
      name = collectionName.toLowerCase(),
      primary = self.schema._primary[name];


  // Don't allow the updating of primary keys
  if(Utils.present(values[primary]) && values[primary] !== criteria.where[primary]) {
    return cb(Errors.adapter.PrimaryKeyUpdate);
  }
  //temp primary key
var primaryValue=values[primary];
  // Delete any primary keys
  delete values[primary];
sails.log('_primary_',primary,primaryValue);
  async.auto({

    // Find all matching records based on the criteria
    findRecords: function(next) {

      // Use the FIND method to get all the records that match the criteria
      self.find(name, criteria, function(err, records) {
        if(err) return next(err);
        next(null, records);
      });
    },

    // Check each Record to update meets the unique constraint rules
    checkUniqueConstraints: ['findRecords', function(next, results) {

      // Get Indices
      var indices = self.schema._indices[name];
      var indiceNames = indices.map(function(idx) { return idx.name; });

      // Check if any unique values are being updated across multiple records
      indiceNames.forEach(function(idx) {
        if(hasOwnProperty(values, idx) && results.findRecords.length > 1) {
          return next(new Error('Attempting to update a unique value on multiple records'));
        }
      });

      self._uniqueConstraint(name, values, function(err) {
        if(err) return next(err);
        next();
      },primaryValue);
    }],

    // Check that any sequences are not being updated
    checkPrimaryKeyValid: ['findRecords', function(next, results) {

      var sequences = self.schema._sequences[name];
      var sequenceNames = sequences.map(function(sequence) { return sequence.name; });

      var valid = true;
      sequences.forEach(function(sequenceNames) {
        if(Utils.present(values[sequenceNames])) {
          valid = false;
        }
      });

      if(!valid) {
        return next(Errors.adapter.InvalidAutoIncrement);
      }

      next();
    }],

    // Update any indexed values that have been created
    updateIndexes: ['checkUniqueConstraints', 'checkPrimaryKeyValid', function(next, results) {

      // Cache original values
      var data = results.findRecords;

      // Get Indices
      var indices = self.schema._indices[name];

      // Use a MULTI wrapper to ensure the removal and creation of indexes happens atomically
      var multi = self.connection.multi();

      // Queue up index operations
      function updateIndex(idx, nextItem) {

        var name = idx.name;
        var key = idx.keyName;

        // Indexed value not updated
        if(!Utils.present(values[name])) return nextItem();

        // Remove the previously indexed values
        data.forEach(function(record) {
          multi.srem(key, record[name]);
        });

        // Add the new indexed value
        multi.sadd(key, values[name]);

        nextItem();
      }

      async.each(indices, updateIndex, function(err) {
        if(err) return next(err);

        // Execute the MULTI set
        multi.exec(function(err, multiResults) {
          if(err) return next(err);
          if(multiResults.indexOf(0) > -1) return next(new Error('Error writing index'));

          next();
        });
      });
    }],

    // Update the record values
    updateRecords: ['updateIndexes', function(next, results) {
      var models = [];

      function updateRecord(item, nextItem) {
        var key = self.schema.recordKey(name, primary, item[primary]);
        var updatedValues = _.extend(item, values);

        self.connection.set(key, JSON.stringify(updatedValues), function(err) {
          if(err) return nextItem(err);
          models.push(updatedValues);
          nextItem();
        });
      }

      async.each(results.findRecords, updateRecord, function(err) {
        if(err) return next(err);
        next(null, models);
      });
    }]

  }, function(err, results) {
    if(err) return cb(err);
    cb(null, results.updateRecords);
  });
};
```

and 


```javascript
Database.prototype._uniqueConstraint = function _uniqueConstraint(collectionName, data, cb,primaryValue) {

  // Grab the indices for this collection
  var indices = this.schema._indices[collectionName];
  // If there are no indices for this collection, return true
  if(indices.length === 0) return cb(null, true);

  // Create a MULTI wrapper for this connection
  var multi = this.connection.multi();

    //first we must chceck if there is data primaryKey
    //if yes we want to check idx.name in db if idx.name is equal in db and in data
    //we dont check the uniqueness because we are only updating - not inserting
    var primary=this.schema._primary[collectionName];
    sails.log('primary key',primary,primaryValue);
    sails.log('data',data);
    if(data){
		if(!primaryValue){
			uniqueness(null,data,cb);
		}else{
		
			var recordKey=this.schema.recordKey(collectionName, primary, primaryValue);

			this.connection.get(recordKey,function(err,dbData){
				if(err)cb(err);
				try{
					dbData=JSON.parse(dbData);
				}catch(e){
					cb(e);
				}
				uniqueness(dbData,data,cb);
			});
		}
    }else{
	    cb(new Error("No data to update"));
    }
    function uniqueness(dbData,data,cb){
	    // For each sequence, add an query to check if the index exists
	    var updating=[];
		indices.forEach(function(idx) {
			// If no value is set, ignore it
			if(!hasOwnProperty(data, idx.name)) return;
			if(dbData){
				if(hasOwnProperty(dbData,idx.name)){
					if(dbData[idx.name]==data[idx.name]){
						updating[idx.name]=true;
						//updating - do not check that this value already exists
						return;
					}else{
						multi.sismember(idx.keyName, data[idx.name]);
					}
				}
			}else{
				//if values in data and in database are not equal we must check new value
				multi.sismember(idx.keyName, data[idx.name]);
			}
			
			})
			
			// Run the MULTI wrapped transaction checking that the results are all falsy
			multi.exec(function(err, results) {
			  if(err)return cb(err);
			  var unique = true;
			  results = results || [];

			  // For each of the results, if any are truthy then the value is not unique
			  results.forEach(function(res) {
			    if(res)unique = false;
			  });

			  // If unique is false return an error
			  if(!unique) return cb(Errors.adapter.NotUnique);

			  // If everything was unique, create each of the indexes
			  async.each(indices, function(idx, next) {
			    // If no value is set, ignore it
			    if(!hasOwnProperty(data, idx.name))return next();
			    
			    if(!updating[idx.name]){
				    idx.index(data[idx.name], next);
			    }else{
				    next();
			    }

			  }, function(err) {
			    if(err){sails.log.error(err); return cb(err);}
			    cb();
			  });
			});
    }
  

  
};
```

**Comment by chipgata** [comment]
It's not work!
Still error

```
AdapterError: Record does not satisfy unique constraints
    at /Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/lib/database/index.js:833:41
    at /Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/node_modules/redis/index.js:1170:13
    at try_callback (/Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (/Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/node_modules/redis/index.js:321:14)
    at HiredisReplyParser.emit (events.js:107:17)
    at HiredisReplyParser.execute (/Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/chipgata/Projects/backend-tracking-marketing/node_modules/sails-redis/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

Details:  AdapterError: Record does not satisfy unique constraints
```

 "sails-redis": "^0.10.3",
 "sails": "~0.11.0",
Thanks you

**Comment by camel-chased** [comment]
try nohm - it is not so popular but much better than waterline redis driver

**Comment by Ryanc1256** [comment]
@chipgata @camel-chased I'm pretty sure with the pull request #67 this should be fixed cant really confirm without a test case or something though

**Comment by ronenteva** [comment]
I encountered the same problem on 0.10.4
create item A - ok
create item B - ok
add many to many relationship between A and B - AdapterError: Record does not satisfy unique constraints

Ended up using mysql instead

**Comment by Ryanc1256** [comment]
Same Problem as this... Haven't had much time to work on it sadly ;( 

https://github.com/balderdashy/sails-redis/issues/24

**Comment by carlospliego** [comment]
Getting the same problem on 10.7

**Comment by Illizian** [comment]
@Ryanc1256 This need's re-opening as this issue is still plaguing the adapter!

**Comment by Ryanc1256** [comment]
@Illizian it doesn't due to this issue being a duplicate of #24

**Comment by Illizian** [comment]
@Ryanc1256 ok, #24 is related to the `save` method. I assumed the logic was slightly different. Thanks!

**Comment by Ryanc1256** [comment]
@Illizian an it's the same problem just worded differently... but yeah... it's quite annoying... i would love to fix it, but I'm tired on waiting for the other guys to pull in changes to another repo ( It's been like 5 months at least )

**Comment by Illizian** [comment]
@Ryanc1256 ok, I have an idea for a fix for but it feel's like a large undertaking. Is the fix ready and waiting for this other repo or is it in the other repo.

Are there any patches I could use temporarily?

**Comment by Ryanc1256** [comment]
@Illizian yeah this bug is super hard to fix... its a bug with the whole adapter tbh... and I have a fix for a massive bunch of issues here...
